### ISSUE TITLE
Docs navigation issues

### ISSUE THREAD

**Issue by uncenter** [umami-software/website#131]
In the process of editing and reviewing the documentation I realized a few issues that were negatively impacting my experience enough to make an issue about.

## Scrolling issues
When scrolling down a long page, the side menu doesn't begin to scroll until near the bottom because it doesn't have it's own independent scrolling. If I click on an item in the side menu towards the bottom and the new section loads, the scroll position resets - meaning you can't easily switch between sections and keep track of your place. A good example that we should try to emulate is https://nextjs.org/docs.

## Image quality

It seems like the images are super blurry to me! Not super important but just a small QOL thing. It would be nice to retake them and make them appear more consistent as well, and we could add some sort of optimization/processing during build if necessary.

**Comment by devarshishimpi** [comment]
I would love to contribute to this issue along with @gambhirsharma
We both would work on this in a team and provide you with the fix PR while keeping the Contributing Guidelines in mind.
Requesting the team to kindly assign the issue to both of us! Thanks!

**Comment by uncenter** [comment]
Feel free to make a PR that closes this!
