### ISSUE TITLE
Getting started button on homepage should go to docs

### ISSUE THREAD

**Issue by uncenter** [umami-software/website#135]
I think it's odd that the "Getting started" button brings you to Umami Cloud.

<img width="500" alt="image" src="https://github.com/umami-software/website/assets/47499684/70ca8d0a-38c2-48b9-be87-875b4b145dba">

It should go to the "Getting started" docs page, which already has a banner for Umami Cloud right at the top.

<img width="1320" alt="image" src="https://github.com/umami-software/website/assets/47499684/41d39071-40e3-41a1-8795-9bc3fbae5512">

**Comment by devarshishimpi** [comment]
Agreed!

I would love to contribute to this issue along with @gambhirsharma
We both would work on this in a team and provide you with the fix PR while keeping the Contributing Guidelines in mind.
Requesting the team to kindly assign the issue to both of us! Thanks!

**Comment by gambhirsharma** [comment]
Yes please assign us this issue.

**Comment by uncenter** [comment]
Feel free to make a PR that closes this! I brought up this issue because I'm not sure if the team agrees.

**Comment by uncenter** [comment]
I'm just going to note that as an open source project I don't like how you are being intentionally misleading by having the getting started button link to the Cloud option only with no mention of self-hosting.

**Comment by mikecao** [comment]
@uncenter There is a self-host mention right on the sign up page

![image](https://github.com/umami-software/website/assets/477975/2f9e0bbc-cab1-4ae5-b61a-448de2d12395)

**Comment by uncenter** [comment]
Fair, I didn't notice that. I still think it is odd that a product/program like Umami, which is known by many (most?) as an open-souce and self-hostable service, pushes one toward the cloud option. I think the "Getting started" page has a beautiful banner that subtly and effectively does that, and it would make sense for the "Getting started" buttons to go to the "Getting started" page anyway.

![Screenshot 2023-12-16 at 13 07 28 (Arc)](https://github.com/umami-software/website/assets/47499684/9b753abf-234b-4c62-b699-cec628fb2210)
