### ISSUE TITLE
 Uninformative page titles

### ISSUE THREAD

**Issue by uncenter** [umami-software/website#139]
It's pretty difficult to keep track of multiple tabs of Umami when every page has the same title, just "umami". Something like "Terms of Service | umami" or "Terms of Service - umami" would be nice!

![Screenshot 2023-11-03 at 16 14 09 (Arc)](https://github.com/umami-software/website/assets/47499684/e8ec8863-52bb-45bf-a316-aa95cc902521)

**Comment by oneminch** [comment]
I can start working on this.

**Comment by uncenter** [comment]
Go ahead!

**Comment by oneminch** [comment]
Should I capitalize umami as Umami or is it part of the brand? It's currently inconsistent across the main website, the docs and the cloud service website?

**Comment by uncenter** [comment]
Yeah I'm not quite sure either. @mikecao?

**Comment by uncenter** [comment]
Closed by #141.
