### ISSUE TITLE
Umami docs pages are broken

### ISSUE THREAD

**Issue by developomp** [umami-software/website#171]
The umami docs pages are broken since this (https://github.com/umami-software/website/commit/9b9cac8f18c28a883ce3c7737025445a5f09ef50) commit.

screenshot of https://umami.is/docs/running-on-vercel:
![Screenshot_20240422_182333_Brave](https://github.com/umami-software/website/assets/40858122/7301898a-2360-45f2-a535-97e7b80077ea)

**Comment by TreyWW** [comment]
How did you get to the `docs/running-on-vercel` path? When visiting the docs the `guides` tab correctly directs to `/docs/guides/running-on-vercel`. Maybe your browser was in cache, or was there a redirect URL somewhere in the docs that led you to `docs/running-on-vercel`?

**Comment by TreyWW** [comment]
Ah I see, when coming from google chrome the site hasn't been re-indexed so it's still picking up the old docs path

![image](https://github.com/umami-software/website/assets/73353716/035f794e-84a3-44c4-a3c9-06e6b25e3360)

**Comment by developomp** [comment]
Using the `guides` tab does indeed bring me to the right page. Closing as non-bug.
