### ISSUE TITLE
Confusing "Last..." naming 

### ISSUE THREAD

**Issue by edgarasben** [umami-software/website#172]
I was getting confused about why I don't see any data when I select "Last 6 months" or "Last 24 hours." I just realized that this means the **previous** 6 months.

In many tools, "Last 6 months" typically includes the current month as well as the five preceding months.

Perhaps a better wording would be "Past 6 months" or "Previous 6 months" for example?

<img width="242" alt="image" src="https://github.com/umami-software/website/assets/725324/ebb30670-6a0d-4ef6-9a5e-d9d601e73d27">

**Comment by mikecao** [comment]
Which version are you using? We had an issue where we were showing the wrong data, which should be fixed in the latest. When you select Last X, it will now always include the current time period.

**Comment by edgarasben** [comment]
`v2.11.2` , it's the latest I guess?

**Comment by mikecao** [comment]
This is what I see when I select last 6 months on the latest version

![image](https://github.com/umami-software/website/assets/477975/2f052c3e-8efa-42e4-a425-2f670f149ecf)

Is this not what you're seeing?
