### ISSUE TITLE
Broken docs page under some conditions (Tracker configuration)

### ISSUE THREAD

**Issue by BamBalaam** [umami-software/website#68]
Hi team,

The current build of the website has a [broken page](https://umami.is/docs/tracker-config) in the docs.

**Comment by BamBalaam** [comment]
# Additional info

Error displayed on page

> Application error: a client-side exception has occurred (see the browser console for more information).

Errors in the browser console

> TypeError: NetworkError when attempting to fetch resource.
> A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
> Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.

**Comment by BamBalaam** [comment]
# Additional info, episode II

It works fine if I load the webpage directly. This error happens if I access it from the Menu on the left.

**Comment by mikecao** [comment]
Fixed now. Thanks for the report!
