### ISSUE TITLE
UI : Add support for showing active link on sidebar.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [umami-software/website#82]
Currently, if the user clicks on the sidebar link we do not show the active state for the link. it is hard for the user to identify on which page they are.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59080942/194616392-79b3e485-ee74-47e4-890e-c5bc89cfaea1.png">

I would propose a solution like this showing the active state for the current page in the sidebar.
![image](https://user-images.githubusercontent.com/59080942/194616237-b66cc911-76a3-478f-8ea2-12de3b85e5b4.png)

**Comment by Sachin-chaurasiya** [comment]
I would like to work on this one.

**Comment by uncenter** [comment]
I think this can be closed!

<img width="251" alt="image" src="https://github.com/umami-software/website/assets/47499684/51167c38-9f6d-4fd1-a1d3-a54ffdbb046c">
